<a href="https://colab.research.google.com/github/sattviksahai/CS583B_Recitation/blob/master/midterm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow.keras
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Conv2D, Dense
import numpy as np


In [2]:
input_map = np.random.rand(20,20,6)
print(input_map.shape)

(20, 20, 6)


In [21]:

model = Sequential()
model.add(Conv2D(8, (5,5), strides=(2,2), padding='same', activation='relu', input_shape=(20,20,6)))

model.summary()

Model: "sequential_18"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_18 (Conv2D)           (None, 10, 10, 8)         1208      
Total params: 1,208
Trainable params: 1,208
Non-trainable params: 0
_________________________________________________________________


In [0]:
# dense
model2 = Sequential()
model2.add(Dense(10*10*8, activation='relu', input_shape=(20*20*6,)))

model2.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 800)               1920800   
Total params: 1,920,800
Trainable params: 1,920,800
Non-trainable params: 0
_________________________________________________________________


In [0]:
print(20*20*6*10*10*8)

1920000


In [0]:
print(5*5*6*8)

1200


In [0]:
import torch

In [0]:
x = torch.tensor([[1,2]], dtype=torch.float)
print(x)
print(x.shape)

tensor([[1., 2.]])
torch.Size([1, 2])


In [0]:
w1 = torch.tensor([[2,1, 1],[1,-2, 2]], dtype=torch.float)
w1.requires_grad_(True)
print(w1)
print(w1.shape)

tensor([[ 2.,  1.,  1.],
        [ 1., -2.,  2.]], requires_grad=True)
torch.Size([2, 3])


In [0]:
w2 = torch.tensor([[-1],[3],[2]], dtype=torch.float)
w2.requires_grad_(True)
print(w2)
print(w2.shape)

tensor([[-1.],
        [ 3.],
        [ 2.]], requires_grad=True)
torch.Size([3, 1])


In [0]:
#fp
z = torch.mm(x,w1)
print(z)
z_ = torch.nn.functional.relu(z)
print(z_)
y_ = torch.mm(z_,w2)
print(y_)
# loss
l = torch.pow(torch.sub(y_,0), 2)
print(l)
# back
l.backward()


tensor([[ 4., -3.,  5.]], grad_fn=<MmBackward>)
tensor([[4., 0., 5.]], grad_fn=<ReluBackward0>)
tensor([[6.]], grad_fn=<MmBackward>)
tensor([[36.]], grad_fn=<PowBackward0>)


In [0]:
# print
print(w1.grad.data)
print(w2.grad.data)

tensor([[-12.,   0.,  24.],
        [-24.,   0.,  48.]])
tensor([[48.],
        [ 0.],
        [60.]])


In [0]:
alpha = 0.1
w1_new = w1 - (alpha*w1.grad.data)
w2_new = w2 - (alpha*w2.grad.data)

In [0]:
print(w1_new)
print(w2_new)

tensor([[ 3.2000,  1.0000, -1.4000],
        [ 3.4000, -2.0000, -2.8000]], grad_fn=<SubBackward0>)
tensor([[-5.8000],
        [ 3.0000],
        [-4.0000]], grad_fn=<SubBackward0>)


In [0]:
print(w1_new[0,0].data)
print(w1_new[1,0].data)
print(w1_new[0,1].data)
print(w1_new[1,1].data)
print(w1_new[0,2].data)
print(w1_new[1,2].data)

tensor(3.2000)
tensor(3.4000)
tensor(1.)
tensor(-2.)
tensor(-1.4000)
tensor(-2.8000)
