In [1]:
import numpy as np
np.random.seed(0)

### Question 1 ###

In [2]:
vec = np.array([2,5,-10,-7,-7])

mat = np.array([[-3, -1, 9],
                [8, -6, -4],
                [2, -9, -4]])

In [17]:
print("x = ", vec)
print("X = ", mat)

x =  [  2   5 -10  -7  -7]
X =  [[ 1 -1  3 21]
 [ 3 -6  9 -9]
 [ 2 -1  6 10]
 [ 4  0 12  4]]


In [4]:
np.linalg.norm(vec, ord=np.inf)

10.0

In [5]:
np.linalg.norm(mat, ord='fro')

17.549928774784245

### Question 2 ###

In [6]:
mat = np.array([[1, -1, 3, 21],
                [3, -6, 9, -9],
                [2, -1, 6, 10],
                [4, 0, 12, 4]])

In [18]:
print("X = ", mat)

X =  [[ 1 -1  3 21]
 [ 3 -6  9 -9]
 [ 2 -1  6 10]
 [ 4  0 12  4]]


In [8]:
print(np.linalg.matrix_rank(mat))

3


### Question 3 ###

In [12]:
A = np.array([[1, -1, 3, 21],
            [3, -6, 9, -9],
            [2, -1, 6, 10]])

B = np.array([[2, 5, -10],
            [-7, -7, -3],
            [-1, 9, 8],
            [-6, -4, 2]])

In [19]:
print("A = ", A)
print("B = ", B)

A =  [[ 1 -1  3 21]
 [ 3 -6  9 -9]
 [ 2 -1  6 10]]
B =  [[  2   5 -10]
 [ -7  -7  -3]
 [ -1   9   8]
 [ -6  -4   2]]


In [20]:
print(np.matmul(A,B))

[[-120  -45   59]
 [  93  174   42]
 [ -55   31   51]]
